"""adds Author model, and refactors Book model to establish a relationship with Author

Revision ID: 165960de2d10
Revises: 9a48c07a31c4
Create Date: 2022-11-03 20:21:45.927663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165960de2d10'
down_revision = '9a48c07a31c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('book', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book', 'author', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'author_id')
    op.drop_table('author')
    # ### end Alembic commands ###
